version: "3.8"
services:
  ##########################
  # CONTENEURS APPLICATIFS #
  ##########################

#  # attacker Debian 12
#  attacker:
#    container_name: attacker
#    image: debian:12
#    tty: true
#    networks:
#      - bank-offsec-external
#    volumes:
#      - ./docker/files:/home/documents
#      - ./docker/scripts:/home/scripts
  attacker:
    # https://docs.linuxserver.io/images/docker-rdesktop/#version-tags
    #image: ubuntu-browser:8.12.23
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: attacker
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=100O
      - PGID=1000
      - TZ=Europe/Paris
      #- SUBFOLDER=/ #optional
      - TITLE=Student-Ubuntu-KDE #optional
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - ./docker/files:/tmp/share/files
      - ./docker/scripts:/tmp/share/scripts
    ports:
      - '3000:3000'
      - '3001:3001'
    #    devices:
    #      - /dev/dri:/dev/dri #optional
    shm_size: "4gb" #optional
    restart: unless-stopped
    networks:
      - bank-offsec-external

  # target-site
  target-site:
    container_name: target-site
    build: ./docker/php
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./app:/var/www
    restart: always
    networks:
      - bank-offsec-external
      - bank-offsec-internal


  ##########################
  # CONTENEURS SERVICES    #
  ##########################

  #Base de données Mysql
  # si vous souhaitez utilisé l'image: mysql:5.7, decommenté la ligne platform
  db:
    container_name: db
    image: mariadb:10.5.8 # mysql:5.7
    # platform: linux/amd64
    restart: always
    volumes:
      - ./data/db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - bank-offsec-internal
  #PHP My Admin
#  phpmyadmin:
#    container_name: pma
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - "8081:80"
#    environment:
#      PMA_HOST: db
#    networks:
#      - bank-offsec-internal

# Définition de réseaux
networks:
  bank-offsec-internal:
  bank-offsec-external: